application:
  name: api-gateway

server:
  port: 443

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8080/realms/mentorlink-dev
            jwk-set-uri: http://localhost:8080/realms/mentorlink-dev/protocol/openid-connect/certs