server:
  port: ${SERVER_PORT}
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<remaining>.*), /${remaining}

            - id: users-service
              uri: ${USER_SERVICE_URI}
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<remaining>.*), /${remaining}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}